deployment:
 tasks:
 # Make a MeowBase folder  in the user's home directory. 
 - mkdir -p ~/public_html/MeowBase
 # Copy Repository to MeowBase folder
 - cp -R * ~/public_html/MeowBase
 # Make sure that Apache can access the folder
